run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - revive
    - gosec
    - gocyclo
    - depguard
    - dupl

linters-settings:
  depguard:
    rules:
      Main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use github.com/bborbe/errors instead"
          - pkg: "github.com/bborbe/argument"
            desc: "use github.com/bborbe/argument/v2 instead"
          - pkg: "golang.org/x/net/context"
            desc: "use context from standard library instead"
          - pkg: "golang.org/x/lint/golint"
            desc: "deprecated, use revive or staticcheck instead"
          - pkg: "io/ioutil"
            desc: "deprecated since Go 1.16, use io and os packages instead"

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019" # allow deprecated in specific cases
    - linters:
        - revive
      path: "_test\\.go$"
      text: "dot-imports"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - dupl
      path: "_test\\.go$"
