apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: '{{ "NAMESPACE" | env }}-skeleton'
  namespace: strimzi
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
